# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='name',
        ),
        migrations.AddField(
            model_name='period',
            name='unit',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='paycheck',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
