# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20160831_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='unit',
            field=models.FloatField(default=0.5),
        ),
        migrations.RemoveField(
            model_name='work',
            name='period',
        ),
        migrations.AddField(
            model_name='work',
            name='period',
            field=models.ForeignKey(default=0.5, on_delete=django.db.models.deletion.CASCADE, to='timeline.Period'),
        ),
    ]
